### ISSUE TITLE
bug/include_orig_elements doesnt include elements metadata / coords

### ISSUE THREAD

**Issue by Depcos** [Unstructured-IO/unstructured-python-client#73] opened 2024-04-26 10:51 UTC
**Describe the bug**
When using:
```python
shared.PartitionParameters(
    coordinates=True,
    strategy="hi_res",
    chunking_strategy="by_title",
    include_orig_elements=True,
)
```
the result in CompositeElement doesnt return .metadata.orig_elements
It doesn't return coordinates for the CompositeElement also. Only works for tables.
Version 0.22.0 returned these metadata but only their memory addresses so that wasnt very usefull.

**To Reproduce**
Provide a code snippet that reproduces the issue.
I use last version 0.23.0 downloaded and builded from github.
```python
s = unstructured_client.UnstructuredClient(
    api_key_auth=api_key,
    server_url=api_url,
)
x_files = shared.Files(
    content=file,
    file_name=file_name,
)
req = shared.PartitionParameters(
    files=x_files,
    coordinates=True,
    split_pdf_page=True,
    hi_res_model_name="detectron2_onnx",
    strategy="hi_res",
    chunking_strategy="by_title",
    include_orig_elements=True,
    max_characters=50,
    combine_under_n_chars=20
)
try:
    resp = s.general.partition(req)
    s.general.sdk_configuration
    return resp.elements
    # print(resp.elements[0])
except SDKError as e:
    print(e)

```

**Expected behavior**
I expect to recieve coordinates for CompositeElement or coordinates for all elements which it was composed from atleast.

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.
Doesnt have this script.
**Additional context**
Normal unstructured returns list of objects with their respective coordinates, so its propably something yet to be implemented.

**Comment by scanny** [comment] 2024-05-08 21:31
Hi @Depcos, `CompositeElement` isn't going to contain coordinates because it is a combination of multiple elements. So that will need to come from `chunk.metadata.orig_elements` and you'll have to decide for your use case how to combine the multiple bounding boxes into one if that's what you need. (The challenge is when there are elements on different pages.)

We'll try to reproduce the `.metadata.orig_elements` being missing. Worth trying it with the latest version of everything in the meantime since it's relatively recently added.

**Comment by Coniferish** [comment] 2024-05-09 14:14
Hi @Depcos! The latest public release (0.22.0) on pypi actually doesn't support `include_orig_elements`. We paused releases because we will be introducing some breaking changes, but we should be changing that soon and when we do `include_orig_elements` will be supported

**Comment by scanny** [comment] 2024-05-09 20:33
@Coniferish @Depcos The default value of `include_orig_elements` is `True`, so it shouldn't need to be provided to get `.metadata.orig_elements` on chunks.

**Comment by scanny** [comment] 2024-05-09 21:40
@Depcos I'm seeing `.metadata.orig_elements` for all chunks when I call the API the way you mentioned.

I'm going to close this as not-a-bug. But let us know if you need more on this.

**Closed by scanny** 2024-05-09 21:40 UTC
Labels: investigating
